In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [30]:
df = pd.read_csv("/content/improved_disease_dataset.csv")

In [31]:
df.head()

fever  headache  nausea  vomiting  fatigue  joint_pain  skin_rash  cough  \
0      1         0       1         0        1           0          0      1   
1      0         0       1         0        0           0          1      1   
2      0         0       1         0        1           0          1      1   
3      0         0       1         1        1           0          1      1   
4      1         0       1         0        1           0          0      0   

   weight_loss  yellow_eyes                       disease  
0            1            0  Paralysis (brain hemorrhage)  
1            0            0  Paralysis (brain hemorrhage)  
2            0            0  Paralysis (brain hemorrhage)  
3            1            1  Paralysis (brain hemorrhage)  
4            1            1  Paralysis (brain hemorrhage)

In [32]:
df.shape

(2000, 11)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   fever        2000 non-null   int64 
 1   headache     2000 non-null   int64 
 2   nausea       2000 non-null   int64 
 3   vomiting     2000 non-null   int64 
 4   fatigue      2000 non-null   int64 
 5   joint_pain   2000 non-null   int64 
 6   skin_rash    2000 non-null   int64 
 7   cough        2000 non-null   int64 
 8   weight_loss  2000 non-null   int64 
 9   yellow_eyes  2000 non-null   int64 
 10  disease      2000 non-null   object
dtypes: int64(10), object(1)
memory usage: 172.0+ KB


In [34]:
df.describe()

fever     headache       nausea     vomiting      fatigue  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean      0.328000     0.413000     0.378500     0.526000     0.365500   
std       0.469602     0.492496     0.485134     0.499448     0.481691   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     1.000000     0.000000   
75%       1.000000     1.000000     1.000000     1.000000     1.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

        joint_pain    skin_rash       cough  weight_loss  yellow_eyes  
count  2000.000000  2000.000000  2000.00000  2000.000000  2000.000000  
mean      0.450500     0.387000     0.55500     0.456000     0.449000  
std       0.497668     0.487185     0.49709     0.498185     0.497517  
min       0.000000     0.000000     0.00000     0.000000     0.000000  
25%       0.000000     0.000000     0.00000     0.000000     0.000000  
50%       0.000000     0.000000     1.00000     0.000000     0.000000  
75%       1.000000     1.000000     1.00000     1.000000     1.000000  
max       1.000000     1.000000     1.00000     1.000000     1.000000

In [35]:
df.isnull().sum()

fever          0
headache       0
nausea         0
vomiting       0
fatigue        0
joint_pain     0
skin_rash      0
cough          0
weight_loss    0
yellow_eyes    0
disease        0
dtype: int64

In [36]:
X = df.drop("disease",axis =1)
y = df["disease"]

In [37]:
print(X)
print(y)

      fever  headache  nausea  vomiting  fatigue  joint_pain  skin_rash  \
0         1         0       1         0        1           0          0   
1         0         0       1         0        0           0          1   
2         0         0       1         0        1           0          1   
3         0         0       1         1        1           0          1   
4         1         0       1         0        1           0          0   
...     ...       ...     ...       ...      ...         ...        ...   
1995      1         1       0         0        1           0          0   
1996      1         0       0         0        1           1          1   
1997      1         0       0         1        0           0          0   
1998      0         0       0         0        1           1          0   
1999      0         0       0         1        1           1          0   

      cough  weight_loss  yellow_eyes  
0         1            1            0  
1         1        

In [38]:
print(X.shape)
print(y.shape)

(2000, 10)
(2000,)


In [39]:
print(X_train.shape)
print(X_test.shape)

(1600, 10)
(400, 10)


In [40]:
print(len(X_train))
print(len(X_test))

1600
400


In [41]:
print(len(y_train))
print(len(y_test))

1600
400


In [42]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [43]:
df.head()

fever  headache  nausea  vomiting  fatigue  joint_pain  skin_rash  cough  \
0      1         0       1         0        1           0          0      1   
1      0         0       1         0        0           0          1      1   
2      0         0       1         0        1           0          1      1   
3      0         0       1         1        1           0          1      1   
4      1         0       1         0        1           0          0      0   

   weight_loss  yellow_eyes                       disease  
0            1            0  Paralysis (brain hemorrhage)  
1            0            0  Paralysis (brain hemorrhage)  
2            0            0  Paralysis (brain hemorrhage)  
3            1            1  Paralysis (brain hemorrhage)  
4            1            1  Paralysis (brain hemorrhage)

In [44]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [45]:
X_scaled = scaler.fit_transform(X)
X_scaled

array([[ 1.43135617, -0.83879527,  1.28140857, ...,  0.89543386,
         1.09223736, -0.90270817],
       [-0.69863813, -0.83879527,  1.28140857, ...,  0.89543386,
        -0.91555191, -0.90270817],
       [-0.69863813, -0.83879527,  1.28140857, ...,  0.89543386,
        -0.91555191, -0.90270817],
       ...,
       [ 1.43135617, -0.83879527, -0.78039122, ..., -1.11677706,
        -0.91555191,  1.10777773],
       [-0.69863813, -0.83879527, -0.78039122, ..., -1.11677706,
        -0.91555191,  1.10777773],
       [-0.69863813, -0.83879527, -0.78039122, ..., -1.11677706,
        -0.91555191,  1.10777773]])

In [46]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.4375

In [47]:
y_pred1 = model.predict(X_test)

In [48]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(accuracy_score(y_pred1,y_test))

0.4375
0.4375


In [28]:
con_matrix = confusion_matrix(y_test,y_pred1)
print(con_matrix)

[[5 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 5 0 0]
 [0 0 0 ... 0 4 0]
 [0 1 0 ... 0 0 8]]


In [49]:
print(classification_report(y_test,y_pred1))

                                                precision    recall  f1-score   support

                                          AIDS       0.71      0.83      0.77         6
                                          Acne       0.30      0.30      0.30        10
                           Alcoholic hepatitis       0.00      0.00      0.00         1
                                       Allergy       0.00      0.00      0.00         9
                                     Arthritis       0.20      0.11      0.14         9
                              Bronchial Asthma       0.14      0.14      0.14         7
                          Cervical spondylosis       0.17      0.25      0.20         8
                           Chronic cholestasis       0.53      0.47      0.50        17
                                        Dengue       0.13      0.33      0.19         6
                                      Diabetes       0.67      0.55      0.60        11
                  Dimorphic hem